/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as CreateWorkspaceRouteImport } from './routes/create-workspace'
import { Route as WorkspaceRouteImport } from './routes/_workspace'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceOrgSlugRouteImport } from './routes/_workspace/$orgSlug'
import { Route as PublicSignupRouteImport } from './routes/_public/signup'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as PublicForgotPasswordRouteImport } from './routes/_public/forgot-password'
import { Route as WorkspaceOrgSlugIndexRouteImport } from './routes/_workspace/$orgSlug/index'
import { Route as WorkspaceOrgSlugWikiRouteImport } from './routes/_workspace/$orgSlug/wiki'
import { Route as WorkspaceOrgSlugTimeRouteImport } from './routes/_workspace/$orgSlug/time'
import { Route as WorkspaceOrgSlugTasksRouteImport } from './routes/_workspace/$orgSlug/tasks'
import { Route as WorkspaceOrgSlugStarredRouteImport } from './routes/_workspace/$orgSlug/starred'
import { Route as WorkspaceOrgSlugSettingsRouteImport } from './routes/_workspace/$orgSlug/settings'
import { Route as WorkspaceOrgSlugRecentRouteImport } from './routes/_workspace/$orgSlug/recent'
import { Route as WorkspaceOrgSlugInboxRouteImport } from './routes/_workspace/$orgSlug/inbox'
import { Route as WorkspaceOrgSlugChatRouteImport } from './routes/_workspace/$orgSlug/chat'
import { Route as WorkspaceOrgSlugAiRouteImport } from './routes/_workspace/$orgSlug/ai'
import { Route as WorkspaceOrgSlugActivityRouteImport } from './routes/_workspace/$orgSlug/activity'
import { Route as WorkspaceOrgSlugTimeIndexRouteImport } from './routes/_workspace/$orgSlug/time/index'
import { Route as WorkspaceOrgSlugTasksIndexRouteImport } from './routes/_workspace/$orgSlug/tasks/index'
import { Route as WorkspaceOrgSlugTimeWeekRouteImport } from './routes/_workspace/$orgSlug/time/week'
import { Route as WorkspaceOrgSlugTimeMonthRouteImport } from './routes/_workspace/$orgSlug/time/month'
import { Route as WorkspaceOrgSlugTasksBoardRouteImport } from './routes/_workspace/$orgSlug/tasks/board'
import { Route as WorkspaceOrgSlugTasksBacklogRouteImport } from './routes/_workspace/$orgSlug/tasks/backlog'
import { Route as WorkspaceOrgSlugTasksAssignedRouteImport } from './routes/_workspace/$orgSlug/tasks/assigned'
import { Route as WorkspaceOrgSlugSettingsWorkspaceRouteImport } from './routes/_workspace/$orgSlug/settings/workspace'
import { Route as WorkspaceOrgSlugSettingsProfileRouteImport } from './routes/_workspace/$orgSlug/settings/profile'
import { Route as WorkspaceOrgSlugSettingsNotificationsRouteImport } from './routes/_workspace/$orgSlug/settings/notifications'
import { Route as WorkspaceOrgSlugSettingsMembersRouteImport } from './routes/_workspace/$orgSlug/settings/members'
import { Route as WorkspaceOrgSlugSettingsBillingRouteImport } from './routes/_workspace/$orgSlug/settings/billing'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateWorkspaceRoute = CreateWorkspaceRouteImport.update({
  id: '/create-workspace',
  path: '/create-workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceOrgSlugRoute = WorkspaceOrgSlugRouteImport.update({
  id: '/$orgSlug',
  path: '/$orgSlug',
  getParentRoute: () => WorkspaceRoute,
} as any)
const PublicSignupRoute = PublicSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const PublicForgotPasswordRoute = PublicForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => PublicRoute,
} as any)
const WorkspaceOrgSlugIndexRoute = WorkspaceOrgSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceOrgSlugRoute,
} as any)
const WorkspaceOrgSlugWikiRoute = WorkspaceOrgSlugWikiRouteImport.update({
  id: '/wiki',
  path: '/wiki',
  getParentRoute: () => WorkspaceOrgSlugRoute,
} as any)
const WorkspaceOrgSlugTimeRoute = WorkspaceOrgSlugTimeRouteImport.update({
  id: '/time',
  path: '/time',
  getParentRoute: () => WorkspaceOrgSlugRoute,
} as any)
const WorkspaceOrgSlugTasksRoute = WorkspaceOrgSlugTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => WorkspaceOrgSlugRoute,
} as any)
const WorkspaceOrgSlugStarredRoute = WorkspaceOrgSlugStarredRouteImport.update({
  id: '/starred',
  path: '/starred',
  getParentRoute: () => WorkspaceOrgSlugRoute,
} as any)
const WorkspaceOrgSlugSettingsRoute =
  WorkspaceOrgSlugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => WorkspaceOrgSlugRoute,
  } as any)
const WorkspaceOrgSlugRecentRoute = WorkspaceOrgSlugRecentRouteImport.update({
  id: '/recent',
  path: '/recent',
  getParentRoute: () => WorkspaceOrgSlugRoute,
} as any)
const WorkspaceOrgSlugInboxRoute = WorkspaceOrgSlugInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => WorkspaceOrgSlugRoute,
} as any)
const WorkspaceOrgSlugChatRoute = WorkspaceOrgSlugChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => WorkspaceOrgSlugRoute,
} as any)
const WorkspaceOrgSlugAiRoute = WorkspaceOrgSlugAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => WorkspaceOrgSlugRoute,
} as any)
const WorkspaceOrgSlugActivityRoute =
  WorkspaceOrgSlugActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => WorkspaceOrgSlugRoute,
  } as any)
const WorkspaceOrgSlugTimeIndexRoute =
  WorkspaceOrgSlugTimeIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspaceOrgSlugTimeRoute,
  } as any)
const WorkspaceOrgSlugTasksIndexRoute =
  WorkspaceOrgSlugTasksIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspaceOrgSlugTasksRoute,
  } as any)
const WorkspaceOrgSlugTimeWeekRoute =
  WorkspaceOrgSlugTimeWeekRouteImport.update({
    id: '/week',
    path: '/week',
    getParentRoute: () => WorkspaceOrgSlugTimeRoute,
  } as any)
const WorkspaceOrgSlugTimeMonthRoute =
  WorkspaceOrgSlugTimeMonthRouteImport.update({
    id: '/month',
    path: '/month',
    getParentRoute: () => WorkspaceOrgSlugTimeRoute,
  } as any)
const WorkspaceOrgSlugTasksBoardRoute =
  WorkspaceOrgSlugTasksBoardRouteImport.update({
    id: '/board',
    path: '/board',
    getParentRoute: () => WorkspaceOrgSlugTasksRoute,
  } as any)
const WorkspaceOrgSlugTasksBacklogRoute =
  WorkspaceOrgSlugTasksBacklogRouteImport.update({
    id: '/backlog',
    path: '/backlog',
    getParentRoute: () => WorkspaceOrgSlugTasksRoute,
  } as any)
const WorkspaceOrgSlugTasksAssignedRoute =
  WorkspaceOrgSlugTasksAssignedRouteImport.update({
    id: '/assigned',
    path: '/assigned',
    getParentRoute: () => WorkspaceOrgSlugTasksRoute,
  } as any)
const WorkspaceOrgSlugSettingsWorkspaceRoute =
  WorkspaceOrgSlugSettingsWorkspaceRouteImport.update({
    id: '/workspace',
    path: '/workspace',
    getParentRoute: () => WorkspaceOrgSlugSettingsRoute,
  } as any)
const WorkspaceOrgSlugSettingsProfileRoute =
  WorkspaceOrgSlugSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => WorkspaceOrgSlugSettingsRoute,
  } as any)
const WorkspaceOrgSlugSettingsNotificationsRoute =
  WorkspaceOrgSlugSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => WorkspaceOrgSlugSettingsRoute,
  } as any)
const WorkspaceOrgSlugSettingsMembersRoute =
  WorkspaceOrgSlugSettingsMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => WorkspaceOrgSlugSettingsRoute,
  } as any)
const WorkspaceOrgSlugSettingsBillingRoute =
  WorkspaceOrgSlugSettingsBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => WorkspaceOrgSlugSettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-workspace': typeof CreateWorkspaceRoute
  '/onboarding': typeof OnboardingRoute
  '/forgot-password': typeof PublicForgotPasswordRoute
  '/login': typeof PublicLoginRoute
  '/signup': typeof PublicSignupRoute
  '/$orgSlug': typeof WorkspaceOrgSlugRouteWithChildren
  '/$orgSlug/activity': typeof WorkspaceOrgSlugActivityRoute
  '/$orgSlug/ai': typeof WorkspaceOrgSlugAiRoute
  '/$orgSlug/chat': typeof WorkspaceOrgSlugChatRoute
  '/$orgSlug/inbox': typeof WorkspaceOrgSlugInboxRoute
  '/$orgSlug/recent': typeof WorkspaceOrgSlugRecentRoute
  '/$orgSlug/settings': typeof WorkspaceOrgSlugSettingsRouteWithChildren
  '/$orgSlug/starred': typeof WorkspaceOrgSlugStarredRoute
  '/$orgSlug/tasks': typeof WorkspaceOrgSlugTasksRouteWithChildren
  '/$orgSlug/time': typeof WorkspaceOrgSlugTimeRouteWithChildren
  '/$orgSlug/wiki': typeof WorkspaceOrgSlugWikiRoute
  '/$orgSlug/': typeof WorkspaceOrgSlugIndexRoute
  '/$orgSlug/settings/billing': typeof WorkspaceOrgSlugSettingsBillingRoute
  '/$orgSlug/settings/members': typeof WorkspaceOrgSlugSettingsMembersRoute
  '/$orgSlug/settings/notifications': typeof WorkspaceOrgSlugSettingsNotificationsRoute
  '/$orgSlug/settings/profile': typeof WorkspaceOrgSlugSettingsProfileRoute
  '/$orgSlug/settings/workspace': typeof WorkspaceOrgSlugSettingsWorkspaceRoute
  '/$orgSlug/tasks/assigned': typeof WorkspaceOrgSlugTasksAssignedRoute
  '/$orgSlug/tasks/backlog': typeof WorkspaceOrgSlugTasksBacklogRoute
  '/$orgSlug/tasks/board': typeof WorkspaceOrgSlugTasksBoardRoute
  '/$orgSlug/time/month': typeof WorkspaceOrgSlugTimeMonthRoute
  '/$orgSlug/time/week': typeof WorkspaceOrgSlugTimeWeekRoute
  '/$orgSlug/tasks/': typeof WorkspaceOrgSlugTasksIndexRoute
  '/$orgSlug/time/': typeof WorkspaceOrgSlugTimeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-workspace': typeof CreateWorkspaceRoute
  '/onboarding': typeof OnboardingRoute
  '/forgot-password': typeof PublicForgotPasswordRoute
  '/login': typeof PublicLoginRoute
  '/signup': typeof PublicSignupRoute
  '/$orgSlug/activity': typeof WorkspaceOrgSlugActivityRoute
  '/$orgSlug/ai': typeof WorkspaceOrgSlugAiRoute
  '/$orgSlug/chat': typeof WorkspaceOrgSlugChatRoute
  '/$orgSlug/inbox': typeof WorkspaceOrgSlugInboxRoute
  '/$orgSlug/recent': typeof WorkspaceOrgSlugRecentRoute
  '/$orgSlug/settings': typeof WorkspaceOrgSlugSettingsRouteWithChildren
  '/$orgSlug/starred': typeof WorkspaceOrgSlugStarredRoute
  '/$orgSlug/wiki': typeof WorkspaceOrgSlugWikiRoute
  '/$orgSlug': typeof WorkspaceOrgSlugIndexRoute
  '/$orgSlug/settings/billing': typeof WorkspaceOrgSlugSettingsBillingRoute
  '/$orgSlug/settings/members': typeof WorkspaceOrgSlugSettingsMembersRoute
  '/$orgSlug/settings/notifications': typeof WorkspaceOrgSlugSettingsNotificationsRoute
  '/$orgSlug/settings/profile': typeof WorkspaceOrgSlugSettingsProfileRoute
  '/$orgSlug/settings/workspace': typeof WorkspaceOrgSlugSettingsWorkspaceRoute
  '/$orgSlug/tasks/assigned': typeof WorkspaceOrgSlugTasksAssignedRoute
  '/$orgSlug/tasks/backlog': typeof WorkspaceOrgSlugTasksBacklogRoute
  '/$orgSlug/tasks/board': typeof WorkspaceOrgSlugTasksBoardRoute
  '/$orgSlug/time/month': typeof WorkspaceOrgSlugTimeMonthRoute
  '/$orgSlug/time/week': typeof WorkspaceOrgSlugTimeWeekRoute
  '/$orgSlug/tasks': typeof WorkspaceOrgSlugTasksIndexRoute
  '/$orgSlug/time': typeof WorkspaceOrgSlugTimeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_public': typeof PublicRouteWithChildren
  '/_workspace': typeof WorkspaceRouteWithChildren
  '/create-workspace': typeof CreateWorkspaceRoute
  '/onboarding': typeof OnboardingRoute
  '/_public/forgot-password': typeof PublicForgotPasswordRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/signup': typeof PublicSignupRoute
  '/_workspace/$orgSlug': typeof WorkspaceOrgSlugRouteWithChildren
  '/_workspace/$orgSlug/activity': typeof WorkspaceOrgSlugActivityRoute
  '/_workspace/$orgSlug/ai': typeof WorkspaceOrgSlugAiRoute
  '/_workspace/$orgSlug/chat': typeof WorkspaceOrgSlugChatRoute
  '/_workspace/$orgSlug/inbox': typeof WorkspaceOrgSlugInboxRoute
  '/_workspace/$orgSlug/recent': typeof WorkspaceOrgSlugRecentRoute
  '/_workspace/$orgSlug/settings': typeof WorkspaceOrgSlugSettingsRouteWithChildren
  '/_workspace/$orgSlug/starred': typeof WorkspaceOrgSlugStarredRoute
  '/_workspace/$orgSlug/tasks': typeof WorkspaceOrgSlugTasksRouteWithChildren
  '/_workspace/$orgSlug/time': typeof WorkspaceOrgSlugTimeRouteWithChildren
  '/_workspace/$orgSlug/wiki': typeof WorkspaceOrgSlugWikiRoute
  '/_workspace/$orgSlug/': typeof WorkspaceOrgSlugIndexRoute
  '/_workspace/$orgSlug/settings/billing': typeof WorkspaceOrgSlugSettingsBillingRoute
  '/_workspace/$orgSlug/settings/members': typeof WorkspaceOrgSlugSettingsMembersRoute
  '/_workspace/$orgSlug/settings/notifications': typeof WorkspaceOrgSlugSettingsNotificationsRoute
  '/_workspace/$orgSlug/settings/profile': typeof WorkspaceOrgSlugSettingsProfileRoute
  '/_workspace/$orgSlug/settings/workspace': typeof WorkspaceOrgSlugSettingsWorkspaceRoute
  '/_workspace/$orgSlug/tasks/assigned': typeof WorkspaceOrgSlugTasksAssignedRoute
  '/_workspace/$orgSlug/tasks/backlog': typeof WorkspaceOrgSlugTasksBacklogRoute
  '/_workspace/$orgSlug/tasks/board': typeof WorkspaceOrgSlugTasksBoardRoute
  '/_workspace/$orgSlug/time/month': typeof WorkspaceOrgSlugTimeMonthRoute
  '/_workspace/$orgSlug/time/week': typeof WorkspaceOrgSlugTimeWeekRoute
  '/_workspace/$orgSlug/tasks/': typeof WorkspaceOrgSlugTasksIndexRoute
  '/_workspace/$orgSlug/time/': typeof WorkspaceOrgSlugTimeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-workspace'
    | '/onboarding'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/$orgSlug'
    | '/$orgSlug/activity'
    | '/$orgSlug/ai'
    | '/$orgSlug/chat'
    | '/$orgSlug/inbox'
    | '/$orgSlug/recent'
    | '/$orgSlug/settings'
    | '/$orgSlug/starred'
    | '/$orgSlug/tasks'
    | '/$orgSlug/time'
    | '/$orgSlug/wiki'
    | '/$orgSlug/'
    | '/$orgSlug/settings/billing'
    | '/$orgSlug/settings/members'
    | '/$orgSlug/settings/notifications'
    | '/$orgSlug/settings/profile'
    | '/$orgSlug/settings/workspace'
    | '/$orgSlug/tasks/assigned'
    | '/$orgSlug/tasks/backlog'
    | '/$orgSlug/tasks/board'
    | '/$orgSlug/time/month'
    | '/$orgSlug/time/week'
    | '/$orgSlug/tasks/'
    | '/$orgSlug/time/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-workspace'
    | '/onboarding'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/$orgSlug/activity'
    | '/$orgSlug/ai'
    | '/$orgSlug/chat'
    | '/$orgSlug/inbox'
    | '/$orgSlug/recent'
    | '/$orgSlug/settings'
    | '/$orgSlug/starred'
    | '/$orgSlug/wiki'
    | '/$orgSlug'
    | '/$orgSlug/settings/billing'
    | '/$orgSlug/settings/members'
    | '/$orgSlug/settings/notifications'
    | '/$orgSlug/settings/profile'
    | '/$orgSlug/settings/workspace'
    | '/$orgSlug/tasks/assigned'
    | '/$orgSlug/tasks/backlog'
    | '/$orgSlug/tasks/board'
    | '/$orgSlug/time/month'
    | '/$orgSlug/time/week'
    | '/$orgSlug/tasks'
    | '/$orgSlug/time'
  id:
    | '__root__'
    | '/'
    | '/_public'
    | '/_workspace'
    | '/create-workspace'
    | '/onboarding'
    | '/_public/forgot-password'
    | '/_public/login'
    | '/_public/signup'
    | '/_workspace/$orgSlug'
    | '/_workspace/$orgSlug/activity'
    | '/_workspace/$orgSlug/ai'
    | '/_workspace/$orgSlug/chat'
    | '/_workspace/$orgSlug/inbox'
    | '/_workspace/$orgSlug/recent'
    | '/_workspace/$orgSlug/settings'
    | '/_workspace/$orgSlug/starred'
    | '/_workspace/$orgSlug/tasks'
    | '/_workspace/$orgSlug/time'
    | '/_workspace/$orgSlug/wiki'
    | '/_workspace/$orgSlug/'
    | '/_workspace/$orgSlug/settings/billing'
    | '/_workspace/$orgSlug/settings/members'
    | '/_workspace/$orgSlug/settings/notifications'
    | '/_workspace/$orgSlug/settings/profile'
    | '/_workspace/$orgSlug/settings/workspace'
    | '/_workspace/$orgSlug/tasks/assigned'
    | '/_workspace/$orgSlug/tasks/backlog'
    | '/_workspace/$orgSlug/tasks/board'
    | '/_workspace/$orgSlug/time/month'
    | '/_workspace/$orgSlug/time/week'
    | '/_workspace/$orgSlug/tasks/'
    | '/_workspace/$orgSlug/time/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PublicRoute: typeof PublicRouteWithChildren
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
  CreateWorkspaceRoute: typeof CreateWorkspaceRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-workspace': {
      id: '/create-workspace'
      path: '/create-workspace'
      fullPath: '/create-workspace'
      preLoaderRoute: typeof CreateWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/$orgSlug': {
      id: '/_workspace/$orgSlug'
      path: '/$orgSlug'
      fullPath: '/$orgSlug'
      preLoaderRoute: typeof WorkspaceOrgSlugRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_public/signup': {
      id: '/_public/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof PublicSignupRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/forgot-password': {
      id: '/_public/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof PublicForgotPasswordRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_workspace/$orgSlug/': {
      id: '/_workspace/$orgSlug/'
      path: '/'
      fullPath: '/$orgSlug/'
      preLoaderRoute: typeof WorkspaceOrgSlugIndexRouteImport
      parentRoute: typeof WorkspaceOrgSlugRoute
    }
    '/_workspace/$orgSlug/wiki': {
      id: '/_workspace/$orgSlug/wiki'
      path: '/wiki'
      fullPath: '/$orgSlug/wiki'
      preLoaderRoute: typeof WorkspaceOrgSlugWikiRouteImport
      parentRoute: typeof WorkspaceOrgSlugRoute
    }
    '/_workspace/$orgSlug/time': {
      id: '/_workspace/$orgSlug/time'
      path: '/time'
      fullPath: '/$orgSlug/time'
      preLoaderRoute: typeof WorkspaceOrgSlugTimeRouteImport
      parentRoute: typeof WorkspaceOrgSlugRoute
    }
    '/_workspace/$orgSlug/tasks': {
      id: '/_workspace/$orgSlug/tasks'
      path: '/tasks'
      fullPath: '/$orgSlug/tasks'
      preLoaderRoute: typeof WorkspaceOrgSlugTasksRouteImport
      parentRoute: typeof WorkspaceOrgSlugRoute
    }
    '/_workspace/$orgSlug/starred': {
      id: '/_workspace/$orgSlug/starred'
      path: '/starred'
      fullPath: '/$orgSlug/starred'
      preLoaderRoute: typeof WorkspaceOrgSlugStarredRouteImport
      parentRoute: typeof WorkspaceOrgSlugRoute
    }
    '/_workspace/$orgSlug/settings': {
      id: '/_workspace/$orgSlug/settings'
      path: '/settings'
      fullPath: '/$orgSlug/settings'
      preLoaderRoute: typeof WorkspaceOrgSlugSettingsRouteImport
      parentRoute: typeof WorkspaceOrgSlugRoute
    }
    '/_workspace/$orgSlug/recent': {
      id: '/_workspace/$orgSlug/recent'
      path: '/recent'
      fullPath: '/$orgSlug/recent'
      preLoaderRoute: typeof WorkspaceOrgSlugRecentRouteImport
      parentRoute: typeof WorkspaceOrgSlugRoute
    }
    '/_workspace/$orgSlug/inbox': {
      id: '/_workspace/$orgSlug/inbox'
      path: '/inbox'
      fullPath: '/$orgSlug/inbox'
      preLoaderRoute: typeof WorkspaceOrgSlugInboxRouteImport
      parentRoute: typeof WorkspaceOrgSlugRoute
    }
    '/_workspace/$orgSlug/chat': {
      id: '/_workspace/$orgSlug/chat'
      path: '/chat'
      fullPath: '/$orgSlug/chat'
      preLoaderRoute: typeof WorkspaceOrgSlugChatRouteImport
      parentRoute: typeof WorkspaceOrgSlugRoute
    }
    '/_workspace/$orgSlug/ai': {
      id: '/_workspace/$orgSlug/ai'
      path: '/ai'
      fullPath: '/$orgSlug/ai'
      preLoaderRoute: typeof WorkspaceOrgSlugAiRouteImport
      parentRoute: typeof WorkspaceOrgSlugRoute
    }
    '/_workspace/$orgSlug/activity': {
      id: '/_workspace/$orgSlug/activity'
      path: '/activity'
      fullPath: '/$orgSlug/activity'
      preLoaderRoute: typeof WorkspaceOrgSlugActivityRouteImport
      parentRoute: typeof WorkspaceOrgSlugRoute
    }
    '/_workspace/$orgSlug/time/': {
      id: '/_workspace/$orgSlug/time/'
      path: '/'
      fullPath: '/$orgSlug/time/'
      preLoaderRoute: typeof WorkspaceOrgSlugTimeIndexRouteImport
      parentRoute: typeof WorkspaceOrgSlugTimeRoute
    }
    '/_workspace/$orgSlug/tasks/': {
      id: '/_workspace/$orgSlug/tasks/'
      path: '/'
      fullPath: '/$orgSlug/tasks/'
      preLoaderRoute: typeof WorkspaceOrgSlugTasksIndexRouteImport
      parentRoute: typeof WorkspaceOrgSlugTasksRoute
    }
    '/_workspace/$orgSlug/time/week': {
      id: '/_workspace/$orgSlug/time/week'
      path: '/week'
      fullPath: '/$orgSlug/time/week'
      preLoaderRoute: typeof WorkspaceOrgSlugTimeWeekRouteImport
      parentRoute: typeof WorkspaceOrgSlugTimeRoute
    }
    '/_workspace/$orgSlug/time/month': {
      id: '/_workspace/$orgSlug/time/month'
      path: '/month'
      fullPath: '/$orgSlug/time/month'
      preLoaderRoute: typeof WorkspaceOrgSlugTimeMonthRouteImport
      parentRoute: typeof WorkspaceOrgSlugTimeRoute
    }
    '/_workspace/$orgSlug/tasks/board': {
      id: '/_workspace/$orgSlug/tasks/board'
      path: '/board'
      fullPath: '/$orgSlug/tasks/board'
      preLoaderRoute: typeof WorkspaceOrgSlugTasksBoardRouteImport
      parentRoute: typeof WorkspaceOrgSlugTasksRoute
    }
    '/_workspace/$orgSlug/tasks/backlog': {
      id: '/_workspace/$orgSlug/tasks/backlog'
      path: '/backlog'
      fullPath: '/$orgSlug/tasks/backlog'
      preLoaderRoute: typeof WorkspaceOrgSlugTasksBacklogRouteImport
      parentRoute: typeof WorkspaceOrgSlugTasksRoute
    }
    '/_workspace/$orgSlug/tasks/assigned': {
      id: '/_workspace/$orgSlug/tasks/assigned'
      path: '/assigned'
      fullPath: '/$orgSlug/tasks/assigned'
      preLoaderRoute: typeof WorkspaceOrgSlugTasksAssignedRouteImport
      parentRoute: typeof WorkspaceOrgSlugTasksRoute
    }
    '/_workspace/$orgSlug/settings/workspace': {
      id: '/_workspace/$orgSlug/settings/workspace'
      path: '/workspace'
      fullPath: '/$orgSlug/settings/workspace'
      preLoaderRoute: typeof WorkspaceOrgSlugSettingsWorkspaceRouteImport
      parentRoute: typeof WorkspaceOrgSlugSettingsRoute
    }
    '/_workspace/$orgSlug/settings/profile': {
      id: '/_workspace/$orgSlug/settings/profile'
      path: '/profile'
      fullPath: '/$orgSlug/settings/profile'
      preLoaderRoute: typeof WorkspaceOrgSlugSettingsProfileRouteImport
      parentRoute: typeof WorkspaceOrgSlugSettingsRoute
    }
    '/_workspace/$orgSlug/settings/notifications': {
      id: '/_workspace/$orgSlug/settings/notifications'
      path: '/notifications'
      fullPath: '/$orgSlug/settings/notifications'
      preLoaderRoute: typeof WorkspaceOrgSlugSettingsNotificationsRouteImport
      parentRoute: typeof WorkspaceOrgSlugSettingsRoute
    }
    '/_workspace/$orgSlug/settings/members': {
      id: '/_workspace/$orgSlug/settings/members'
      path: '/members'
      fullPath: '/$orgSlug/settings/members'
      preLoaderRoute: typeof WorkspaceOrgSlugSettingsMembersRouteImport
      parentRoute: typeof WorkspaceOrgSlugSettingsRoute
    }
    '/_workspace/$orgSlug/settings/billing': {
      id: '/_workspace/$orgSlug/settings/billing'
      path: '/billing'
      fullPath: '/$orgSlug/settings/billing'
      preLoaderRoute: typeof WorkspaceOrgSlugSettingsBillingRouteImport
      parentRoute: typeof WorkspaceOrgSlugSettingsRoute
    }
  }
}

interface PublicRouteChildren {
  PublicForgotPasswordRoute: typeof PublicForgotPasswordRoute
  PublicLoginRoute: typeof PublicLoginRoute
  PublicSignupRoute: typeof PublicSignupRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicForgotPasswordRoute: PublicForgotPasswordRoute,
  PublicLoginRoute: PublicLoginRoute,
  PublicSignupRoute: PublicSignupRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface WorkspaceOrgSlugSettingsRouteChildren {
  WorkspaceOrgSlugSettingsBillingRoute: typeof WorkspaceOrgSlugSettingsBillingRoute
  WorkspaceOrgSlugSettingsMembersRoute: typeof WorkspaceOrgSlugSettingsMembersRoute
  WorkspaceOrgSlugSettingsNotificationsRoute: typeof WorkspaceOrgSlugSettingsNotificationsRoute
  WorkspaceOrgSlugSettingsProfileRoute: typeof WorkspaceOrgSlugSettingsProfileRoute
  WorkspaceOrgSlugSettingsWorkspaceRoute: typeof WorkspaceOrgSlugSettingsWorkspaceRoute
}

const WorkspaceOrgSlugSettingsRouteChildren: WorkspaceOrgSlugSettingsRouteChildren =
  {
    WorkspaceOrgSlugSettingsBillingRoute: WorkspaceOrgSlugSettingsBillingRoute,
    WorkspaceOrgSlugSettingsMembersRoute: WorkspaceOrgSlugSettingsMembersRoute,
    WorkspaceOrgSlugSettingsNotificationsRoute:
      WorkspaceOrgSlugSettingsNotificationsRoute,
    WorkspaceOrgSlugSettingsProfileRoute: WorkspaceOrgSlugSettingsProfileRoute,
    WorkspaceOrgSlugSettingsWorkspaceRoute:
      WorkspaceOrgSlugSettingsWorkspaceRoute,
  }

const WorkspaceOrgSlugSettingsRouteWithChildren =
  WorkspaceOrgSlugSettingsRoute._addFileChildren(
    WorkspaceOrgSlugSettingsRouteChildren,
  )

interface WorkspaceOrgSlugTasksRouteChildren {
  WorkspaceOrgSlugTasksAssignedRoute: typeof WorkspaceOrgSlugTasksAssignedRoute
  WorkspaceOrgSlugTasksBacklogRoute: typeof WorkspaceOrgSlugTasksBacklogRoute
  WorkspaceOrgSlugTasksBoardRoute: typeof WorkspaceOrgSlugTasksBoardRoute
  WorkspaceOrgSlugTasksIndexRoute: typeof WorkspaceOrgSlugTasksIndexRoute
}

const WorkspaceOrgSlugTasksRouteChildren: WorkspaceOrgSlugTasksRouteChildren = {
  WorkspaceOrgSlugTasksAssignedRoute: WorkspaceOrgSlugTasksAssignedRoute,
  WorkspaceOrgSlugTasksBacklogRoute: WorkspaceOrgSlugTasksBacklogRoute,
  WorkspaceOrgSlugTasksBoardRoute: WorkspaceOrgSlugTasksBoardRoute,
  WorkspaceOrgSlugTasksIndexRoute: WorkspaceOrgSlugTasksIndexRoute,
}

const WorkspaceOrgSlugTasksRouteWithChildren =
  WorkspaceOrgSlugTasksRoute._addFileChildren(
    WorkspaceOrgSlugTasksRouteChildren,
  )

interface WorkspaceOrgSlugTimeRouteChildren {
  WorkspaceOrgSlugTimeMonthRoute: typeof WorkspaceOrgSlugTimeMonthRoute
  WorkspaceOrgSlugTimeWeekRoute: typeof WorkspaceOrgSlugTimeWeekRoute
  WorkspaceOrgSlugTimeIndexRoute: typeof WorkspaceOrgSlugTimeIndexRoute
}

const WorkspaceOrgSlugTimeRouteChildren: WorkspaceOrgSlugTimeRouteChildren = {
  WorkspaceOrgSlugTimeMonthRoute: WorkspaceOrgSlugTimeMonthRoute,
  WorkspaceOrgSlugTimeWeekRoute: WorkspaceOrgSlugTimeWeekRoute,
  WorkspaceOrgSlugTimeIndexRoute: WorkspaceOrgSlugTimeIndexRoute,
}

const WorkspaceOrgSlugTimeRouteWithChildren =
  WorkspaceOrgSlugTimeRoute._addFileChildren(WorkspaceOrgSlugTimeRouteChildren)

interface WorkspaceOrgSlugRouteChildren {
  WorkspaceOrgSlugActivityRoute: typeof WorkspaceOrgSlugActivityRoute
  WorkspaceOrgSlugAiRoute: typeof WorkspaceOrgSlugAiRoute
  WorkspaceOrgSlugChatRoute: typeof WorkspaceOrgSlugChatRoute
  WorkspaceOrgSlugInboxRoute: typeof WorkspaceOrgSlugInboxRoute
  WorkspaceOrgSlugRecentRoute: typeof WorkspaceOrgSlugRecentRoute
  WorkspaceOrgSlugSettingsRoute: typeof WorkspaceOrgSlugSettingsRouteWithChildren
  WorkspaceOrgSlugStarredRoute: typeof WorkspaceOrgSlugStarredRoute
  WorkspaceOrgSlugTasksRoute: typeof WorkspaceOrgSlugTasksRouteWithChildren
  WorkspaceOrgSlugTimeRoute: typeof WorkspaceOrgSlugTimeRouteWithChildren
  WorkspaceOrgSlugWikiRoute: typeof WorkspaceOrgSlugWikiRoute
  WorkspaceOrgSlugIndexRoute: typeof WorkspaceOrgSlugIndexRoute
}

const WorkspaceOrgSlugRouteChildren: WorkspaceOrgSlugRouteChildren = {
  WorkspaceOrgSlugActivityRoute: WorkspaceOrgSlugActivityRoute,
  WorkspaceOrgSlugAiRoute: WorkspaceOrgSlugAiRoute,
  WorkspaceOrgSlugChatRoute: WorkspaceOrgSlugChatRoute,
  WorkspaceOrgSlugInboxRoute: WorkspaceOrgSlugInboxRoute,
  WorkspaceOrgSlugRecentRoute: WorkspaceOrgSlugRecentRoute,
  WorkspaceOrgSlugSettingsRoute: WorkspaceOrgSlugSettingsRouteWithChildren,
  WorkspaceOrgSlugStarredRoute: WorkspaceOrgSlugStarredRoute,
  WorkspaceOrgSlugTasksRoute: WorkspaceOrgSlugTasksRouteWithChildren,
  WorkspaceOrgSlugTimeRoute: WorkspaceOrgSlugTimeRouteWithChildren,
  WorkspaceOrgSlugWikiRoute: WorkspaceOrgSlugWikiRoute,
  WorkspaceOrgSlugIndexRoute: WorkspaceOrgSlugIndexRoute,
}

const WorkspaceOrgSlugRouteWithChildren =
  WorkspaceOrgSlugRoute._addFileChildren(WorkspaceOrgSlugRouteChildren)

interface WorkspaceRouteChildren {
  WorkspaceOrgSlugRoute: typeof WorkspaceOrgSlugRouteWithChildren
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceOrgSlugRoute: WorkspaceOrgSlugRouteWithChildren,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PublicRoute: PublicRouteWithChildren,
  WorkspaceRoute: WorkspaceRouteWithChildren,
  CreateWorkspaceRoute: CreateWorkspaceRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
